#pragma once
#include <Windows.h>
#include <stdio.h>
#include <cstdint>
#include <algorithm>
#include <iostream>
#include <vector>
#include <deque>
#include <random>
#include <Psapi.h>
#include <atomic>
#include <chrono>
#include <thread>
#include <assert.h>
#include <string>
//#include <jni.h>
#include <gl\GL.h>
#include <gl\GLU.h>